version: 2.1
commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        default: "world"
        type: string
    steps:
      - run: echo "Hello <<parameters.to>>"
jobs:
  build-1:
    docker: 
      - image: cimg/base:2022.10
    steps:
      - checkout
      - run:
          name: "'run' statements can actually contain a 'name' and 'command' argument as well"
          command: | 
           echo "You can even have multiline commands."
      - restore_cache:
          keys:
          - v1-dependencies-
      - run: echo "testfile" > ~/cache/log.txt
      - save_cache:
          key: v1-dependencies-
          paths: 
            - ~/cache
  build-2:
    docker: # use the docker executor type; machine and macos executors are also supported
      - image: cimg/base:2022.10 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - greeting:
          to: string

workflows:
  build-workflow:
    jobs: 
      - build-1
      - build-2:
          name: first-build-2
