# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# test
# test
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
 build-and-test:
   docker:
     - image: cimg/python:3.11.0
   parallelism: 3
steps:
     - checkout
     - python/install-packages:
         pkg-manager: pip
 
     - run:
         name: Run tests
         command: |
           mkdir test-result
           pytest --collect-only -q | grep -e "\.py" | circleci tests run  --command="xargs pytest --junitxml=test-results/junit.xml -v --" --fail-fast --batch-count=3 --verbose --test-results-path="test-results" --split-by=name
     - store_test_results:
         path: test-results
