version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Add step below to install Ruby version 2.3.8
      - ruby/install:
          version: '2.3'
      - run: ruby -v

workflows:
  run-jobs:
    jobs:
      - build
