version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Add step below to install Ruby version 2.3.8
      - ruby/install:
          version: '2.6'
      - run: ruby -v
      - run:
          command: |
            rvm install 2.3.8
      - run:
          command: |
            echo $CIRCLE_SHA1
            LAST_SHA_REVISION=$(curl -H 'Circle-Token: $CIRCLE_TOKEN' 'https://circleci.com/api/v2/project/github/jkzilla/cci-demo101b/pipeline?branch=master' | jq -r '.items[] | select (.id != << pipeline.id >> ) | select (.state == 'created') | select (.trigger.type == "scheduled_pipeline") | .vcs.revision | head -1';)
            echo $LAST_SHA_REVISION 

workflows:
  run-jobs:
    jobs:
      - build
