version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:2020.01
    steps:
      - run: echo "hello world" # run the `echo` command

workflows:
  my-workflow:
    jobs:
      - hello-job
